function plot_eta(dat, nt)
% PLOT_ETA Plots surface elevations.
%   PLOT_ETA(dat, nt)
%
% INPUTS
%
%   dat - data structs generated by READ_HOS_OCEAN_3D_DAT
%    nt - time index of the surface elevation to be shown
%
% See also READ_HOS_OCEAN_3D_DAT_DEMO.
%
% This function is provided under the same terms as HOS-ocean (GPLv3).

imagesc(dat.eta(:,:,nt).')

[I,J,Nt] = size(dat.eta);
xt = [1 I];
xtlbl = dat.x(xt, 1);
set(gca, 'XTick', xt, 'XTickLabel', xtlbl)
xlabel('x [m]')

yt = [1 J];
ytlbl = dat.y(1, yt);
set(gca, 'YTick', yt, 'YTickLabel', ytlbl)
ylabel('y [m]')

title(sprintf('\\eta(x,y,%gs) [m]', dat.t(nt)));
colorbar;
end